### PR TITLE
Add support for archive pages

### PR DESCRIPTION
**Pull request by benniemosher**
Solves #8 and #24 

Can be demoed at https://benniemosher.com

### CODE REVIEW

**Comment by thelehhman** [comment]
Woudn't it be better if instead of the user creating the category.html file, it is included by default ?

**Comment by benniemosher** [comment]
@thelehhman I tried putting it in the theme, but then when you try and go to `/categories/#Learning` it returns a 404. I put the categories.html in my personal site repo and it renders just fine. I can't figure out why that is or how to fix it. Thoughts?

**Comment by thelehhman** [comment]
Okay it looks great!

Before merging however, please account for the following
1. Update your base branch to include the latest version fix https://github.com/thelehhman/plainwhite-jekyll/issues/24
2. Don't increment version number. Keep it at 0.9. It's yet to be released
3. Rebase all the commits into 2-3 commits max.

Thank you :)

**Comment by benniemosher** [comment]
Created a new PR with an updated base project. This should allow me to rebase off of upstream easier later. https://github.com/thelehhman/plainwhite-jekyll/pull/31

**Pull request closed without merging**
