### PR TITLE
Add basic searchbar

### PR DESCRIPTION
**Pull request by DotIN13**
## Disc
Add basic search functionality with Simple-Jekyll-Search.

## Features
- create search.json
- add searchbar
- basic animations
- focus input on touch
- switch searchbar and animation on/off in _config.yml

### CODE REVIEW

**Comment by DotIN13** [comment]
I've migrated some clumsy css to javascript, and gave the visual a overhaul. Tell me if you like it. @thelehhman

**Comment by thelehhman** [comment]
Great work @DotIN13!
Could you rebase your PR & squash your commits?

**Comment by thelehhman** [comment]
Also, please add a description about the search in the README.

**Comment by DotIN13** [comment]
I have squashed commits and added description to README. Check it out! @thelehhman

**Comment by thelehhman** [comment]
I can't find the search.scss file. Could you check?

**Comment by DotIN13** [comment]
> I can't find the search.scss file. Could you check?

Sorry I made a mistake with `git add`, I'll fix that now.

**Comment by DotIN13** [comment]
Missing files were added, now it should be fine. @thelehhman

**Comment by thelehhman** [comment]
Thanks a lot @DotIN13!
Its a great addition :)

**Comment by DotIN13** [comment]
Glad ya liked it! Cheers! @thelehhman

**Pull request merged**
