### PR TITLE
Added sitemap.xml for SEO

### PR DESCRIPTION
**Pull request by kloiahack**
How do you think about creating a sitemap.xml file for the Google Search Engine? 

I'm using it already, check it out. [Here is a result of generating a sitemap.xml](https://jkpark.me/sitemap.xml)

### CODE REVIEW

**Comment by thelehhman** [comment]
Nice addition. I think an option to toggle the sitemap in `_config.yml` would be a useful addition to this.

**Comment by kloiahack** [comment]
Thank you for your comment. I have the following questions.
1. How do you think about to add a sitemap option in `_config.yml` globally or in plainwhite section? 
2. If a sitemap option is set to *false*, what `sitemap.xml` content will be rendered?

**Comment by thelehhman** [comment]
1. In the plainwhite section
2. You could do something like this in the sitemap.xml file:
```
{%-if site.plainwhite.sitemap -%}
    // generated content
{%- endif -%}
```

**Comment by kloiahack** [comment]
I added the `sitemap` option. The default 'sitemap' option value is true. If necessary, you can change the default value!

Best regards.

**Comment by thelehhman** [comment]
Yeah, add it to the README file and squash your commits into one so that I could proceed with the merge.

**Comment by kloiahack** [comment]
I write a sitemap manual to the README and squash my commits. Check it out please.

**Comment by thelehhman** [comment]
Great!

**Pull request merged**
