### PR TITLE
Add archives, add jekyll-menus support, fix RSS

### PR DESCRIPTION
**Pull request by benniemosher**
Adds custom logo location to use Gravatar or other hosting.

Closes: https://github.com/thelehhman/plainwhite-jekyll/issues/8

### CODE REVIEW

**Comment by benniemosher** [comment]
@thelehhman This PR catches up and rebases my changes that you had requested in https://github.com/thelehhman/plainwhite-jekyll/pull/28

**Comment by thelehhman** [comment]
Thanks @benniemosher.
There's a problem with this PR though , i.e. we can't use jekyll-menus because github pages doesn't support it. Github pages compatibility is highly desired.

**Comment by benniemosher** [comment]
@thelehhman suggested course here? I need jekyll-menus to support forestry.io, but would prefer to not verge from your repository here. Suggestions?

**Comment by thelehhman** [comment]
What purpose does jekyll-menus serve?

**Comment by benniemosher** [comment]
It allows you to build menus based off of a data file, or off of front matter in the post/page. Forestry.io has a really nice UI built in that requires jekyll-menus to work, that is why I am trying to migrate there.

**Comment by thelehhman** [comment]
Move the archives and RSS to a separate PR.
I don't think we need this menus feature.

**Pull request closed without merging**
